export const ACTION_ADD_CONTACT = 'ADD_CONTACT';
export const ACTION_CLEAR_FILTER = 'CLEAR_FILTER';
export const ACTION_DELETE_CONTACT = 'DELETE_CONTACT';
export const ACTION_FILTER_CONTACTS = 'FILTER_CONTACTS';
export const ACTION_UPDATE_CONTACT = 'UPDATE_CONTACT';

export const ACTION_CLEAR_CURRENT = 'CLEAR_CURRENT';
export const ACTION_SET_CURRENT = 'SET_CURRENT';

export const ACTION_REMOVE_ALERT = 'REMOVE_ALERT';
export const ACTION_SET_ALERT = 'SET_ALERT';
